// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5nzHlUzZ_Ky87fzN7DXcA6HH5HKfKCM',
    appId: '1:1092015186513:web:d4d2024014e0cd01ab8e70',
    messagingSenderId: '1092015186513',
    projectId: 'lost-found-enis',
    authDomain: 'lost-found-enis.firebaseapp.com',
    storageBucket: 'lost-found-enis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wnAx0ABkep-fuViXJur6Ux8VzF5Z6fM',
    appId: '1:1092015186513:android:c938b57a1ca69b1dab8e70',
    messagingSenderId: '1092015186513',
    projectId: 'lost-found-enis',
    storageBucket: 'lost-found-enis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYUnu4hbFuLLibCQSwls3dTfhlEOm9XGk',
    appId: '1:1092015186513:ios:78ad3c55909cdb0aab8e70',
    messagingSenderId: '1092015186513',
    projectId: 'lost-found-enis',
    storageBucket: 'lost-found-enis.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundEnis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYUnu4hbFuLLibCQSwls3dTfhlEOm9XGk',
    appId: '1:1092015186513:ios:78ad3c55909cdb0aab8e70',
    messagingSenderId: '1092015186513',
    projectId: 'lost-found-enis',
    storageBucket: 'lost-found-enis.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundEnis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5nzHlUzZ_Ky87fzN7DXcA6HH5HKfKCM',
    appId: '1:1092015186513:web:214350275c91ae7cab8e70',
    messagingSenderId: '1092015186513',
    projectId: 'lost-found-enis',
    authDomain: 'lost-found-enis.firebaseapp.com',
    storageBucket: 'lost-found-enis.firebasestorage.app',
  );
}
